# -------------------------------
# Prefix
# -------------------------------
unbind C-b
unbind r
set -g prefix C-s
bind C-s send-prefix
bind r source-file ~/.config/tmux/tmux.conf

# -------------------------------
# Terminal & Mouse
# -------------------------------
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# -------------------------------
# Pane navigation (vim style)
# -------------------------------
set -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# -------------------------------
# Window navigation
# -------------------------------
bind -n M-H previous-window
bind -n M-L next-window

# -------------------------------
# Indexing
# -------------------------------
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# -------------------------------
# Plugins
# -------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'thepante/tmux-git-autofetch'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'jrmoulton/tmux-sessionizer'

source-file ~/.config/tmux/matugen.conf

# -------------------------------
# Session navigation
# -------------------------------
bind C-o display-popup -E "~/.config/scripts/ghq-session.sh"
bind C-j display-popup -E "tms switch"

# Continuum settings
set -g @continuum-restore 'off'
set -g @continuum-save-interval '15'  # saves every 15 minutes

# Resurrect settings
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'  # Optional, if you use Neovim

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
