background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8917
    brightness = 0.6
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Time
label {
    monitor =
    text = $TIME
    font_size = 72
    font_family = Meslo LG S Bold
    color = rgba(192, 202, 245, 0.9)
    position = 0, 200
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B"
    font_size = 18
    font_family = Meslo LG S
    color = rgba(122, 162, 247, 0.7)
    position = 0, 130
    halign = center
    valign = center
}

# User
label {
    monitor =
    text =   $USER
    font_size = 14
    font_family = Noto Sans Mono
    color = rgba(192, 202, 245, 0.5)
    position = 0, 20
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 220, 44
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = -1
    rounding = 12
    outer_color = rgba(255, 158, 100, 0.6)
    inner_color = rgba(26, 27, 38, 0.7)
    font_color = rgba(192, 202, 245, 0.9)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <span foreground="##a9b1d6">󰌾  password</span>
    hide_input = false
    check_color = rgba(255, 158, 100, 0.9)
    fail_color = rgba(247, 118, 142, 0.9)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fail_transition = 300
    capslock_color = rgba(224, 175, 104, 0.9)
    position = 0, -30
    halign = center
    valign = center
}
