general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 20%    # dim screen after 5min
    on-resume = brightnessctl -r             # restore brightness
}

listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock  # lock screen after 10min
}

listener {
    timeout = 900
    on-timeout = systemctl suspend           # sleep after 15min idle
}
