source = ~/.config/hypr/keybind.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf

monitor = ,preferred,auto,auto

exec-once = waybar
exec-once = swaync
exec-once = swww-daemon
exec-once = vicinae server

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1

general {
    gaps_in = 4
    gaps_out = 12

    border_size = 2

    layout = dwindle

    resize_on_border = false

    col.active_border = rgba(b38d59ee)
    col.inactive_border = rgba(3d3d3daa)
}

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0
    force_no_accel = 1
    numlock_by_default = true
}

cursor {
    no_hardware_cursors = true
}

decoration {
    active_opacity = 0.95
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0
    rounding = 12
    rounding_power = 2.0

    blur {
        enabled = true
        size = 3
        passes = 2
    }

    shadow {
        enabled = false
    }
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}


windowrule = float on, match:title ^(hyprmon)$
windowrule = center on, match:title ^(hyprmon)$
windowrule = size 1000 700, match:title ^(hyprmon)$
