$mainMod = Super

$term = ghostty
$launcher = vicinae toggle
$powermenu = ~/.config/rofi/powermenu/type-1/powermenu.sh
$volume = ~/.config/rofi/applets/bin/volume.sh
$waybar = ~/.config/waybar/scripts/launch.sh
$monitor = hyprmon
$hyprlock = hyprlock

bind = $mainMod, Q, killactive
bind = $mainMod+Ctrl, Q, exec, $hyprlock
bind = $mainMod, Delete, exit
bind = $mainMod+Shift, R, exec, hyprctl reload
bind = $mainMod, R, exec, $waybar
bind = $mainMod+Shift, S, exec, hyprshot -m region

bind = $mainMod, V, togglefloating
bind = $mainMod, F, fullscreen
bind = $mainMod, P, pseudo
bind = $mainMod, Y, pin

bind = $mainMod, Return, exec, $term
bind = $mainMod, Space, exec, $launcher
bind = $mainMod, Backspace, exec, $powermenu || pkill rofi
bind = $mainMod+Shift, V, exec, $volume || pkill rofi
bind = $mainMod+Shift, P, exec, $term --title=hyprmon -e $monitor

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bindm = $mainMod+Shift, mouse:273, resizewindow

bindm = $mainMod+Shift, mouse:272, movewindow
bind = $mainMod+Shift, 1, movetoworkspace, 1
bind = $mainMod+Shift, 2, movetoworkspace, 2
bind = $mainMod+Shift, 3, movetoworkspace, 3
bind = $mainMod+Shift, 4, movetoworkspace, 4
bind = $mainMod+Shift, 5, movetoworkspace, 5
bind = $mainMod+Shift, 6, movetoworkspace, 6
bind = $mainMod+Shift, 7, movetoworkspace, 7
bind = $mainMod+Shift, 8, movetoworkspace, 8
bind = $mainMod+Shift, 9, movetoworkspace, 9
bind = $mainMod+Shift, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod+Alt, S, movetoworkspacesilent, special
bind = $mainMod, S, togglespecialworkspace,

bind = $mainMod+Alt, 1, movetoworkspacesilent, 1
bind = $mainMod+Alt, 2, movetoworkspacesilent, 2
bind = $mainMod+Alt, 3, movetoworkspacesilent, 3
bind = $mainMod+Alt, 4, movetoworkspacesilent, 4
bind = $mainMod+Alt, 5, movetoworkspacesilent, 5
bind = $mainMod+Alt, 6, movetoworkspacesilent, 6
bind = $mainMod+Alt, 7, movetoworkspacesilent, 7
bind = $mainMod+Alt, 8, movetoworkspacesilent, 8
bind = $mainMod+Alt, 9, movetoworkspacesilent, 9
bind = $mainMod+Alt, 0, movetoworkspacesilent, 10
